language: bash

services: docker

os: windows

before_script:
  - docker version
  - env | sort

script:
  - |
    (
      set -Eeuo pipefail
      set -x

      # build:
      docker build --tag rocker-win:latest --file latest/Dockerfile .
      
      # test:
      docker run --rm -it rocker-win R.exe --version
      docker run --rm -it rocker-win Rscript.exe -e "sessionInfo()"
    )

after_script:
  - docker images
